name: Tests

on: 
    push:
        branches:
            - '*'
            - '!master'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.1

            - name: Installing Firebase tools
              run: sudo npm install -g firebase-tools
            
            - uses: c-hive/gha-yarn-cache@v1

            - name: Installing Dependencies
              run: yarn install

            - name: Setting up Firebase emulators
              run: firebase setup:emulators:firestore
      
            - name: Testing against Firebase emulators
              run: firebase emulators:exec --only firestore --token "${{ secrets.FIREBASE_TOKEN }}" --project "${{ secrets.FIREBASE_PROJECT_ID }}" "yarn test"
                